options:
 logging: CLOUD_LOGGING_ONLY
projectId: $PROJECT_ID

steps:

  - name: 'gcr.io/cloud-builders/git'
    entrypoint: /bin/bash
    args:
    - -c
    - |
      git fetch --depth=2 origin main
      git fetch origin $BRANCH_NAME
      git switch $BRANCH_NAME
      git log --name-only origin/main..$BRANCH_NAME -- | grep "/" | cut -d/ -f1-2 | sort | uniq > /workspace/diff.txt
      echo count_projects_changed: $(wc -l /workspace/diff.txt)

  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: /bin/bash
    args:
    - -c
    - |
      while read line; do
        project_name=$(echo $line | cut -d/ -f2)
        config="${line}/cloudbuild.yaml"
        echo $config $project_name
        # if [[ ! -f "${config}" ]]; then
        #   echo "no such file"
        #   continue
        # fi
        # gcloud builds submit . --git-source-dir=${line}/
      done < /workspace/diff.txt
