steps:

  - name: 'gcr.io/cloud-builders/git'
    entrypoint: /bin/bash
    args:
    - -c
    - |
      git fetch --depth=2 origin main
      git fetch origin $BRANCH_NAME
      git switch $BRANCH_NAME
      git diff --name-only main..$BRANCH_NAME --
      git diff --name-only @{u}..$BRANCH_NAME -- | grep "/" | cut -d/ -f1-2 | sort | uniq > /workspace/diff.txt
      cat /workspace/diff.txt
      echo got here
      echo count_projects_changed: $(wc -l /workspace/diff.txt)

  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: /bin/bash
    args:
    - -c
    - |
      while read line; do
        config="${line}/cloudbuild.yaml"
        echo $config
        if [[ ! -f "${config}" ]]; then
          echo "no such file"
          continue
        fi
        gcloud builds submit $line --config=${config}
      done < /workspace/diff.txt


options:
 logging: CLOUD_LOGGING_ONLY
