on:
  pull_request_target:
    types:
      - closed

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "The PR was merged" > status.txt
        git config --global user.name $(git log -1 --pretty=fornat:'%aN')
        git config --global user.email $(git log -1 --pretty=fornat:'%aE')
        git add .
        git commit -m "commit a file"
        git push origin main
        
